#!/usr/bin/env php
<?php

set_time_limit(0);

if (is_file($autoload = getcwd() . '/vendor/autoload.php')) {
    require $autoload;
}
else if (is_dir($vendor = __DIR__ . '/../vendor')) {
    require($vendor . '/autoload.php');
} elseif (is_dir($vendor = __DIR__ . '/../../..')) {
    require($vendor . '/autoload.php');
} else {
    die(
        'You must set up the project dependencies, run the following commands:' . PHP_EOL .
        'curl -s http://getcomposer.org/installer | php' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
}

require_once __DIR__.'/AppKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'test');
$debug = $env === 'dev';

if ($debug) {
    Debug::enable();
}

$kernel = new test\Vivait\TenantBundle\app\AppKernel($env, $debug);
$application = new Application($kernel);
$application->run($input);
